// Package hookfile renders the small POSIX shell script installed as the
// git commit-msg hook, and detects whether an existing file at that
// location was put there by git-commit-sentinel.
package hookfile

import (
	"fmt"
	"strings"
)

// Marker identifies a hook file as managed by git-commit-sentinel. Its
// presence lets `setup` overwrite its own previous installs without
// clobbering a hook the user wrote by hand.
const Marker = "# managed-by: git-commit-sentinel"

// BinaryName is the executable `setup` expects to find on PATH at commit
// time.
const BinaryName = "git-commit-sentinel"

// Render returns the commit-msg hook script content.
func Render() string {
	return fmt.Sprintf(
		"#!/bin/sh\n%s\n# Do not edit by hand: re-run `%s setup` to regenerate.\nexec %s hook \"$1\"\n",
		Marker, BinaryName, BinaryName,
	)
}

// IsManaged reports whether content was generated by Render (in this or an
// earlier version), identified by the marker comment.
func IsManaged(content string) bool {
	return strings.Contains(content, Marker)
}
